# -*- coding: utf-8 -*-
"""
/***************************************************************************
 calculobeiral
                                 A QGIS plugin
 Este plugin calcula a área de beirais de edificações
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-31
        copyright            : (C) 2026 by Stephany Souza
        email                : stephany.cristina@ufpr.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load calculobeiral class from file calculobeiral.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .calc_beiral import calculobeiral
    return calculobeiral(iface)
