# -*- coding: utf-8 -*-
"""
/***************************************************************************
 calculobeiral
                                 A QGIS plugin
 Este plugin calcula a área de beirais de edificações
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-31
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Stephany Souza
        email                : stephany.cristina@ufpr.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication, QVariant
from qgis.core import *
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox

# Import the code for the dialog
from .calc_beiral_dialog import calculobeiralDialog
import os.path
import processing
import sys, os
from osgeo import ogr


class calculobeiral:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Cálculo de Beiral')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str

        :returns: Translated version of message.
        :rtype: str
        """
        return QCoreApplication.translate('calculobeiral', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'casa.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Cálculo de Beiral'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Cálculo de Beiral'),
                action)
            self.iface.removeToolBarIcon(action)

    def carregaVetor(self):
        """Preenche o combobox com as layers vetoriais existentes no projeto"""
        self.dlg.comboBox.clear()
        lista_layers = [layer for layer in QgsProject.instance().mapLayers().values()]
        lista_layers_vetor = []
        for layer in lista_layers:
            if layer.type() == QgsMapLayer.VectorLayer:
                lista_layers_vetor.append(layer.name())
        self.dlg.comboBox.addItems(lista_layers_vetor)
        
    def abrirVetor(self):
        """abre a janela de diálogo para abrir uma layer"""
        camada_abrir = str(QFileDialog.getOpenFileName(caption = "Escolha a camada...", filter="Shapefiles (*.shp)")[0])
        if (camada_abrir != ""):
            self.iface.addVectorLayer(camada_abrir, str.split(os.path.basename(camada_abrir),".")[0], "ogr")
            self.carregaVetor()
                
        
    def carregaVetor2(self):
        """Preenche o combobox com as layers vetoriais existentes no projeto"""
        self.dlg.comboBox_2.clear()
        lista_layers2 = [layer for layer in QgsProject.instance().mapLayers().values()]
        lista_layers_vetor2 = []
        for layer in lista_layers2:
            if layer.type() == QgsMapLayer.VectorLayer:
                lista_layers_vetor2.append(layer.name())
        self.dlg.comboBox_2.addItems(lista_layers_vetor2)
        
    def abrirVetor2(self):
        """abre a janela de diálogo para abrir uma layer a ser aplicada o buffer"""
        camada_abrir2 = str(QFileDialog.getOpenFileName(caption = "Escolha a camada...", filter="Shapefiles (*.shp)")[0])
        if (camada_abrir2 != ""):
            self.iface.addVectorLayer(camada_abrir2, str.split(os.path.basename(camada_abrir2),".")[0], "ogr")
            self.carregaVetor2()
            
            
    def camadaEnt (self):
        """Obter a layer definida no combobox_2"""
        layer = None
        nomecamada = self.dlg.comboBox_2.currentText()
        for lyr in QgsProject.instance().mapLayers().values():
            if lyr.name() == nomecamada:
                layer = lyr
                break
        return layer
    
    def definirSaida (self):
        """abre a janela de diálogo para definir o local de saída da camada de resultado"""
        camada_salvar = str(QFileDialog.getSaveFileName(caption = "Defina a camada de saída...", filter="Shapefiles (*.shp)")[0])
        self.dlg.lineEdit.setText(camada_salvar)
        
    def variaveis(self):
        """define as variaveis utilizadas na função run"""
        self.camada = self.camadaEnt()
        self.saida = self.dlg.lineEdit.text()
        self.largura = self.dlg.doubleSpinBox.value()
    
    def validarCamada(self, camada):
        """Valida se a camada existe, se é vetorial e se possui um SRC válido."""
        if not camada:
            QMessageBox.critical(self.iface.mainWindow(), "Erro", "Nenhuma camada de entrada foi selecionada ou encontrada.")
            return False
            
        if camada.type() != QgsMapLayer.VectorLayer or not camada.isValid():
            QMessageBox.critical(self.iface.mainWindow(), "Erro", f"A camada '{camada.name()}' não é um vetor válido.")
            return False
            
        crs = camada.crs()
        if not crs.isValid():
            QMessageBox.critical(self.iface.mainWindow(), "Erro", f"A camada '{camada.name()}' não possui um Sistema de Referência Executivo (SRC) definido.")
            return False
            
        if crs.isGeographic():
            QMessageBox.warning(self.iface.mainWindow(), "Aviso de Projeção", 
                                f"A camada '{camada.name()}' está em coordenadas geográficas (graus).\n\n"
                                "O cálculo do buffer e de áreas pode não funcionar em metros. Recomenda-se usar uma projeção métrica (ex: UTM).")

        return True
    
    def run(self):
        """Run method that performs all the real work"""

        # O segredo está aqui: Conectamos os botões APENAS no primeiro início
        if self.first_start == True:
            self.first_start = False
            self.dlg = calculobeiralDialog()
            
            # Conecta os cliques dos botões uma única vez na vida do plugin
            self.dlg.toolButton.clicked.connect(self.abrirVetor)
            self.dlg.toolButton_2.clicked.connect(self.abrirVetor2)
            self.dlg.toolButton_3.clicked.connect(self.definirSaida)

        # Atualiza os comboboxes toda vez que a janela abre para pegar novas camadas do projeto
        self.carregaVetor()
        self.carregaVetor2()       
        
        # Mostra a janela
        self.dlg.show()
        result = self.dlg.exec()
        
        if result:
            self.variaveis()
            
            # --- VALIDAÇÃO DOS DADOS DE ENTRADA ---
            if not self.validarCamada(self.camada):
                return  
                
            if not self.saida or self.saida.strip() == "":
                QMessageBox.critical(self.iface.mainWindow(), "Erro", "Por favor, defina um arquivo de saída válido.")
                return

            nome_edif = self.dlg.comboBox.currentText()
            camada_edif = None
            for lyr in QgsProject.instance().mapLayers().values():
                if lyr.name() == nome_edif:
                    camada_edif = lyr
                    break
                    
            if camada_edif and not self.validarCamada(camada_edif):
                return  
            # --------------------------------------

            # aplicando o buffer - usando a ferramenta do processamento do QGIS
            try:
                buffer = processing.run("native:singlesidedbuffer", {
                    'INPUT': QgsProcessingFeatureSourceDefinition(
                        self.camada.id(), 
                        selectedFeaturesOnly=False, 
                        featureLimit=-1, 
                        flags=QgsProcessingFeatureSourceDefinition.FlagCreateIndividualOutputPerInputFeature, 
                        geometryCheck=QgsFeatureRequest.GeometryAbortOnInvalid
                    ),
                    'SIDE': 0,
                    'DISTANCE': self.largura,
                    'JOIN_STYLE': 0, 
                    'OUTPUT': self.saida
                })
            except Exception as e:
                QMessageBox.critical(self.iface.mainWindow(), "Erro no Processamento", f"Falha ao gerar o buffer: {str(e)}")
                return
            
            # 1. Carrega a camada de saída (Buffer) no QGIS e obtém a referência dela
            if not os.path.exists(self.saida):
                QMessageBox.critical(self.iface.mainWindow(), "Erro de Salvamento", "O arquivo de saída não foi gerado pelo algoritmo.")
                return

            nome_saida = str.split(os.path.basename(self.saida), ".")[0]
            camada_saida = self.iface.addVectorLayer(self.saida, nome_saida, "ogr")
            
            # 2. Obtém a referência da camada de entrada
            camada_entrada = self.camada

            # --- CÁLCULO E ADIÇÃO DA ÁREA TOTAL NA CAMADA EDIFICAÇÃO ---
            if camada_edif and camada_saida:
                # Garante que o provedor de dados permita modificações
                pr = camada_edif.dataProvider()
                
                # Adiciona a coluna se ela não existir
                idx_coluna = camada_edif.fields().indexFromName('area_total')
                if idx_coluna == -1:
                    pr.addAttributes([QgsField('area_total', QVariant.Double, 'Double', 10, 3)])
                    camada_edif.updateFields()
                    idx_coluna = camada_edif.fields().indexFromName('area_total')

                # Inicia a edição da camada de edificação
                camada_edif.startEditing()
                
                # --- BUSCA DE CAMPOS INSENSÍVEL A MAIÚSCULAS/MINÚSCULAS ---
                def obter_nome_campo_id(camada):
                    for campo in camada.fields():
                        if campo.name().upper() == 'ID_E':
                            return campo.name()
                    return None

                nome_id_saida = obter_nome_campo_id(camada_saida)
                nome_id_edif = obter_nome_campo_id(camada_edif)

                # Se o campo ID_E não existir em alguma das camadas, exibe aviso e aborta
                if not nome_id_saida or not nome_id_edif:
                    QMessageBox.warning(self.iface.mainWindow(), "Campo Não Encontrado", 
                                        "Não foi possível localizar o campo 'ID_E' nas tabelas de atributos.\n"
                                        "Certifique-se de que ambas as camadas possuem essa coluna.")
                    camada_edif.rollBack()
                    return

                # 1. Mapeia as áreas do buffer (beiral) agrupadas por ID_E (em formato string limpa)
                areas_saida_por_id = {}
                for f_saida in camada_saida.getFeatures():
                    val_id = f_saida[nome_id_saida]
                    if val_id is not None and str(val_id).strip() != "":
                        id_chave = str(val_id).strip()
                        # Acumula a área caso haja mais de um segmento de buffer para o mesmo ID
                        areas_saida_por_id[id_chave] = areas_saida_por_id.get(id_chave, 0.0) + f_saida.geometry().area()
                
                # 2. Itera pelas edificações e aplica a regra de correspondência de chaves
                for f_edif in camada_edif.getFeatures():
                    area_e = f_edif.geometry().area()
                    val_id_edif = f_edif[nome_id_edif]
                    
                    id_chave_edif = str(val_id_edif).strip() if val_id_edif is not None else ""
                    
                    # CONDIÇÃO PEDIDA: Se o ID existir no buffer, soma. Caso contrário, considera apenas a área da edificação (area_s = 0.0)
                    area_s = areas_saida_por_id.get(id_chave_edif, 0.0)
                    area_total_calc = area_e + area_s
                    
                    # Atualiza o atributo da feição na tabela
                    camada_edif.changeAttributeValue(f_edif.id(), idx_coluna, area_total_calc)
                
                # Salva as alterações
                camada_edif.commitChanges()

                # --- CONFIGURAÇÃO DO MAP TIP ---
                html_tip = """
                <div style="background-color: #333; color: #fff; padding: 5px; border-radius: 3px;">
                    <b>Área Total:</b> [% format_number("area_total", 2) %] m²
                </div>
                """
                camada_edif.setMapTipTemplate(html_tip)
                camada_edif.setMapTipsEnabled(True)
                
                if not self.iface.actionMapTips().isChecked():
                    self.iface.actionMapTips().trigger()

            # --- ESTILIZAÇÃO DAS CAMADAS ---
            if camada_entrada:
                symbol = camada_entrada.renderer().symbol()
                if symbol:
                    symbol.setColor(QColor(255, 127, 0))
                    camada_entrada.triggerRepaint()

            if camada_edif:
                symbol = camada_edif.renderer().symbol()
                if symbol:
                    symbol.setColor(QColor(255, 0, 0, 127))
                    camada_edif.triggerRepaint()

            if camada_saida:
                symbol = camada_saida.renderer().symbol()
                if symbol:
                    symbol.setColor(QColor(227, 176, 34, 127))
                    camada_saida.triggerRepaint()
                    
            if camada_entrada:
                self.iface.layerTreeView().refreshLayerSymbology(camada_entrada.id())
            if camada_edif:
                self.iface.layerTreeView().refreshLayerSymbology(camada_edif.id())
            if camada_saida:
                self.iface.layerTreeView().refreshLayerSymbology(camada_saida.id())

            pass